//CATEGORY DATA
export const GET_CATEGORY = "GET_CATEGORY"
export const LOADING_CATEGORY = "LOADING_CATEGORY"
export const ERROR_CATEGORY = "ERROR_CATEGORY"
export const POST_CATEGORY = "POST_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPADATE_CATEGORY = "UPADATE_CATEGORY"

//PRODUCT DATA
export const GET_PRODUCT = "GET_PRODUCT"
export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const POST_PRODUCT = "PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPADATE_PRODUCT = "UPADATE_PRODUCT"

//ADD TO CART
export const ADD_CART = "ADD_CART"
export const POST_CART = "POST_CART"
export const DELETE_CART = "DELETE_CART"
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"
export const GET_CART = "GET_CART"
export const ERROR_CART = "ERROR_CART"
export const UPADATE_CART = "UPADATE_CART"
export const LOADING_CART = "LOADING_CART"

//REDUX-SAGAS
export const SIGNUP_USER = "SIGNUP_USER"
export const EMAIL_VERYFICATON = "EMAIL_VERYFICATON"

//SIGNUP ALERT
export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

//LOGIN
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_LOGD = "LOGIN_LOGD"

//LOGOUT
export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_LOGED = "LOGOUT_LOGED"

//GOOGLE SIGNUP
export const GOOGLE_SIGNUP = "GOOGLE_SIGNUP"

//FORGET PASSWORD
export const FORGET_PASSWORD = "FORGET_PASSWORD"

//NEXT PAGE
export const NEXT_ADDTOCART = "NEXT_ADDTOCART"