//CATEGORY DATA
export const GET_CATEGORY = "GET_CATEGORY"
export const LOADING_CATEGORY = "LOADING_CATEGORY"
export const ERROR_CATEGORY = "ERROR_CATEGORY"
export const POST_CATEGORY = "POST_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPADATE_CATEGORY = "UPADATE_CATEGORY"

//PRODUCT DATA
export const GET_PRODUCT = "GET_PRODUCT"
export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const POST_PRODUCT = "PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPADATE_PRODUCT = "UPADATE_PRODUCT"

//ADD TO CART
export const ADD_CART = "ADD_CART"
export const POST_CART = "POST_CART"
export const GET_CART = "GET_CART"